Repository Julessh05/Financer, pull requests merged in 2023-05, with the labels that each got.

#116 Fix Bug
  iOS/Financer/FinancerTests/UserWrapperTests.swift
  shared/Models/Wrappers/UserWrapper.swift
Labels: view, mobile, backend, fix

#117 Tests
  iOS/Financer/Financer.xcodeproj/xcshareddata/xcschemes/FinancerTests.xcscheme
  iOS/Financer/Financer.xcodeproj/xcshareddata/xcschemes/FinancerUITests.xcscheme
Labels: code, backend

#123 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: repo

#125 Create iOS-bugfix-pullrequest.md
  .github/PULL_REQUEST_TEMPLATE/iOS-bugfix-pullrequest.md
Labels: repo

#126 Create docs
  docs/README.md
Labels: documentation, repo

#128 Remove Save Button fix #127
  iOS/Financer/Financer/Views/Components/Editor/FinanceEditor.swift
Labels: view, mobile, fix

#129 Feature/icloud 0
  iOS/Financer/Financer.xcodeproj/project.pbxproj
  iOS/Financer/Financer/Financer.entitlements
  iOS/Financer/Financer/Info.plist
  shared/Storage/Persistence.swift
Labels: minor-feature, mobile
